#!/usr/bin/env tsx
// =============================================================================
// Build-time entry: parse the probe text and emit src/data/probe.ts
// =============================================================================

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseProbe } from "../src/lib/parse-probe";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const srcText = resolve(root, "../icm-hpc/probing_results/master_probe_RESULTS_GPU.txt");
const dstTs = resolve(root, "src/data/probe.ts");

const text = readFileSync(srcText, "utf8");
const snapshot = parseProbe(text);

mkdirSync(dirname(dstTs), { recursive: true });

const banner = `// AUTO-GENERATED by scripts/parse-probe.ts. Do not edit by hand.
// Source: icm-hpc/probing_results/master_probe_RESULTS_GPU.txt

import type { ClusterSnapshot } from "@/lib/types";

`;

const body = `export const clusterSnapshot: ClusterSnapshot = ${JSON.stringify(snapshot, null, 2)};\n`;

writeFileSync(dstTs, banner + body, "utf8");

const sectionCount = Object.keys(snapshot).length;
const gpuCount = snapshot.gpus.length;
const partitionCount = snapshot.partitions.length;
const nfsCount = snapshot.nfsMounts.length;
const moduleCount = snapshot.modules.length;
const vendoredLibsMissing = snapshot.vendoredCuda.libs.filter((l) => !l.inLdPath).length;

console.log(
  `[parse-probe] ✓ wrote ${dstTs}\n` +
    `              ${sectionCount} top-level fields · ${gpuCount} GPUs · ${partitionCount} partitions · ${nfsCount} NFS mounts · ${moduleCount} modules\n` +
    `              vendored CUDA: ${vendoredLibsMissing} sublibs missing from LD_LIBRARY_PATH${vendoredLibsMissing > 0 ? "  ⚠" : ""}`,
);
